MONSTER_LIFE_RANDOMNESS = 0.1
MOSTER_STRENGHT_RANDOMNESS = 0.2

COEF_STRENGHT_TO_EXP = 1
COEF_LOGISTICS_TO_EXP = 1
COEF_GOLD_TO_EXP = 1
COEF_WAR_EXP_TO_EXP = 1

BASE_HIT_CHANCE = 0.5
BASE_DEFENSE_CHANCE = 0.5
BASE_LIFE_POINTS = 100
